# config.py

# --- [新增] 模拟控制参数 ---
SIMULATION_RUNS = 100        # 整个模拟重复的次数，用于取平均值
RECOVERY_REPETITIONS = 100    # 在每个退出步骤中，为获得恢复延迟平均值而重复的次数

# --- 基本模拟参数 ---
INITIAL_HOST_NODES = 50
BLOCK_SIZE_MB = 100.0
NETWORK_SPEED_GBPS = 1.0
BYZANTINE_PERCENTAGE = 0.33
TREE_DEPTH = 1

# --- 方案核心参数 ---
WEIGHT_A = 0.5
WEIGHT_B = 0.5
NETWORK_CONNECTION_OVERHEAD_R = 0.1

# --- 辅助计算参数 ---
RS_COMPUTE_TIME_PER_MB = 0.002
PIECE_METADATA_SIZE_BYTES = 24
HOMOMORPHIC_FINGERPRINT_SIZE_BYTES = 32
HF_COMPUTE_TIME_PER_MB = 0.001
HF_VERIFY_FIXED_TIME = 0.001

# --- 节点退出参数 ---
EXIT_PERCENTAGE_STEP = 0.05
MAX_EXIT_PERCENTAGE = 0.80
